import { makeStyles, shorthands } from '@fluentui/react-components';

export const useStyles = makeStyles({
  base: {
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
    maxWidth: '281px',
    maxHeight: 'fit-content',
    padding: '16px 12px',
    alignItems: 'center',
    justifyContent: 'center',
    boxSizing: 'border-box',
  },
  search: {
    minWidth: '210px',
    backgroundColor: '#F5F5F5',
    ...shorthands.border('none'),
    '&:after': { display: 'none' },
  },
  action: { padding: 0, maxWidth: '16px', minWidth: '16px', height: '16px' },

  header: {
    width: '100%',
    '& *': {
      margin: 0,
    },
  },
  subtitle: {
    display: 'flex',
    gap: '4px',
    alignItems: 'center',
    color: '#666666',
    fontSize: '14px',
  },
  title: {
    color: '#333333',
    fontWeight: '600',
    marginTop: '4px',
    fontSize: '16px',
  },
  labels: { display: 'flex', flexDirection: 'row', gap: '4px' },
  label: {
    color: '#333333',
    fontSize: '11px',
    backgroundColor: '#DAFFBE',
    borderRadius: '2px',
    padding: '1px 4px',
    height: 'auto',
    minHeight: 'auto',
    marginTop: '6px',
  },
  userInfo: { marginTop: '10px' },
  user: { display: 'flex', flexDirection: 'row', alignItems: 'center' },
  avatar: { width: '30px', height: '30px' },
  name: { marginLeft: '3px' },
  badge: {
    alignItems: 'center',
    gap: '3px',
    backgroundColor: '#ffffff',
    color: '#333333',
    boxShadow: '0px 2px 1px -1px #00000033',
    borderRadius: '68px',
    padding: '3px 6px',
    zIndex: 2,
    left: '-5px',
    fontSize: '10px',
  },
  date: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: '4px',
    marginTop: '4px',
    fontSize: '14px',
    color: '#666666',
  },
  dot: {
    display: 'inline-flex',
    width: '3px',
    height: '3px',
    borderRadius: '50%',
    overflow: 'hidden',
    backgroundColor: '#6E7073',
  },
  info: {
    width: '100%',
  },
  desc: {
    fontSize: '12px',
    display: 'inline-block',
    margin: 0,
    '& *': {
      display: 'inline',
      margin: 0,
    },
    '& img': {
      width: '100%',
      height: 'auto',
    },
  },
  readMore: {
    margin: 0,
    marginLeft: '5px',
    color: '#384EC1',
    fontSize: '12px',
  },
  tags: {
    display: 'flex',
    flexDirection: 'row',
    gap: '8px',
    flexWrap: 'wrap',
    marginTop: '10px',
  },
  tag: {
    margin: 0,
    lineHeight: '12px',
    color: '#333333',
    fontSize: '12px',
    borderRadius: '56px',
    padding: '8px 12px',
    border: '1px solid #DDDDDD',
  },
});
